---

# In future this should be included directly on main.yml instead on each role.
#- include_vars: group_vars/general_definitions

# some systems require yum-utils
- name: Some systems require install the yum-utils package to use yum list
  package:
    name: yum-utils

#
# validar versão do CentOS
##########################
- name: Validar versão do Sistema Operativo
  fail: msg="ATENÇÃO, esta versão de Sitema Operativo não é compativel com este pacote de instalação de Shibboleth 3.4.3"
  when: "ansible_os_family != 'RedHat' and ansible_distribution_major_version != '7'"

#
# Validar Java JDK
########################################
- name: Validar se Java 7 está instalado
  yum:
    list: java-1.7.*-openjdk.*
  register: old_java_version

# - debug: var=old_java_version.results[0].yumstate

- name: Check Java 7 instalado?
  fail: msg="ATENÇÃO, Java openjdk 1.7 já instalado!!! É altamente recomendado que a máquina não tenho tido qualuqer instalação de java inferior a à versão 1.8 previamente. É muito provavel que a instalação irá falhar no final!"
  when: old_java_version.results[0].yumstate == "installed"  # installed|available

#
# Validar PostgreSQL
#################################
- name: Validar PostgreSQL Server
  yum: list=postgresql-server
  register: old_postgresql_server

- debug: var=old_postgresql_server.results[0].yumstate

- name: Check PostgreSQL Server instalado?
  fail: msg="ATENÇÃO, PostgreSQL Server já instalado!!!"
  when: old_postgresql_server.results[0].yumstate == "installed"  # installed|available

#- debug: var=old_postgresql_server.stdout

#
# Validar a existencia da chave do certificado do Apache 
######################################################
- name: Validar a existencia da "Chave" do certificado
  stat: path="{{ path_ssl_cert_key_file }}"
  register: cert_key_exists

# - debug: var=cert_key_exists.stat.exists

- name: Check existencia da "Chave" do certificado
  fail: msg="ATENÇÃO, ficheiro {{ path_ssl_cert_key_file }} não encontrado!!"
  when: cert_key_exists.stat.exists == false

#
# Validar a existencia do certificado do Apache 
######################################################
- name: Validar a existencia do certificado
  stat: path="{{ path_ssl_cert_file }}"
  register: cert_file_exists

# - debug: var=cert_file_exists.stat.exists

- name: Check existencia do "Certificado"
  fail: msg="ATENÇÃO, ficheiro {{ path_ssl_cert_file }} não encontrado!!"
  when: cert_file_exists.stat.exists == false

#
# Validar a existencia da CA do Apache 
######################################################
- name: Validar a existencia do CA
  stat: path="{{ path_ssl_cert_chain_file }}"
  register: cert_ca_exists

# - debug: var=cert_ca_exists.stat.exists

- name: Check existencia da "CA"
  fail: msg="ATENÇÃO, ficheiro {{ path_ssl_cert_chain_file }} não encontrado!!"
  when: cert_ca_exists.stat.exists == false